name: pinecone
description: Unofficial Dart client for Pinecone vector database. For more details on Pinecone, please visit https://docs.pinecone.io/docs/overview.
version: 0.6.0
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/pinecone
issue_tracker: https://github.com/tazatechnology/pinecone/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/pinecone

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ">=0.13.0 <2.0.0"
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
dev_dependencies:
  openapi_spec: ^0.6.0
  build_runner: ^2.4.6
  lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  test: ^1.24.7
